### ISSUE TITLE
REVEL prediction missing?

### ISSUE THREAD

**Issue by sczakihl** [bihealth/reev#262] opened 2023-12-07 15:08 UTC
**Describe the bug**
REVEL score missing for some missense variants, but e.g. in varsome a REVEL score is provided.

**To Reproduce**
1. Go to https://reev.cubi.bihealth.org/variant/6:165827027:A:C/grch37 or https://reev.cubi.bihealth.org/variant/8:53049985:G:A/grch37
3. Scroll down to Scores
4. See REVEL missing - compare to varsome

**Expected behavior**

**Screenshots**
Variant PDE10A:
![grafik](https://github.com/bihealth/reev/assets/94172011/f590011c-40b3-4c13-a402-44c17c70e030)
in varsome:
![grafik](https://github.com/bihealth/reev/assets/94172011/f1bc7e41-916b-4515-8027-53d185ac5120)

Variant ST18:
![grafik](https://github.com/bihealth/reev/assets/94172011/73438235-3737-484e-a25b-3e3c4123df6f)
in varsome:
![grafik](https://github.com/bihealth/reev/assets/94172011/51b75e77-e041-4cd2-8476-b0381c9bdfdc)

**Comment by holtgrewe** [comment] 2023-12-10 13:21
This is caused by installing the "fit for commercial" version from dbNSFP rather than "fit for academic". Should be fixed now.

**Closed** 2023-12-10 13:47 UTC
Labels: bug
